language: node_js
node_js:
- stable
services:
  - postgresql
addons:
  postgresql: "9.4"
before_install:
  - npm install coveralls
  - psql -c "CREATE USER puritybirir;" -U postgres
  - NODE_ENV=test
  - psql -c 'create database dms-test;' -U postgres
services:
  - postgresql
script:
  - npm test