language: node_js
node_js:
- stable
addons:
  postgresql: "9.3"
  apt:
   sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
  - npm install -g node-gyp
  - npm install coveralls
  - psql -c 'drop database if exists "dms-test";' -U postgres
  - psql -c 'create database "dms-test";' -U postgres
services:
  - postgresql
script:
  - npm test
after_success:
  - coveralls
